GreptimeTeam/promql-parser

src/parser/ast.rs

According to the go version, the field `offset` is with type `Duration` rather than `Instant`:
```go
// SubqueryExpr represents a subquery.
type SubqueryExpr struct {
Expr  Expr
Range time.Duration
// OriginalOffset is the actual offset that was set in the query.
// This never changes.
OriginalOffset time.Duration
// Offset is the offset used during the query execution
// which is calculated using the original offset, at modifier time,
// eval time, and subquery offsets in the AST tree.
Offset     time.Duration
Timestamp  *int64
StartOrEnd ItemType // Set when @ is used with start() or end()
Step       time.Duration
EndPos Pos
}
```
and
```go
// VectorSelector represents a Vector selection.
type VectorSelector struct {
Name string
// …
```

fix: change offset type to Duration

---

src/parser/ast.rs
src/parser/mod.rs

This patch
- Public `EvalStmt`
- Change `Instant` to `SystemTime`. Because the constant `UNIX_EPOCH` is with type `SystemTime`. To convert to timestamp we need to subtract (`duration_since`) `UNIC_EPOCH`.

feat: replace Instant with SystemTime

---

src/label/matcher.rs
src/parser/ast.rs
src/parser/function.rs

Derive `Clone` attribute for `Expr`. This can make it easy to use on planning.

feat: derive Clone for Expr

---

src/label/matcher.rs
src/parser/ast.rs

Like `sqlparser`, I public all the fields of public structs. They are parts of the parser APIs by themselves. Please remind me if I forget some fields/structs.

chore: pub all fields of pub structs

---

src/parser/ast.rs

Derive `Debug` and `Clone` for `EvalStmt`. I also tried to derive `PartialEq` and `Eq`, but `f64` is not full-ordered, and `Regex` cannot be compared.

feat: derive Debug and Clone for EvalStmt

---

src/label/matcher.rs
src/label/mod.rs
src/parser/ast.rs
src/parser/function.rs
src/parser/mod.rs
src/parser/promql.y
src/parser/token.rs

- use enum to refactor ast instead of optional fields to match
- implement PartialEq, Eq trait for the ease of comparison
- some `Expr::new_` functions, which will be used in `promql.y` in next PR

feat(ast): impl PartialEq, Eq for Expr

---

src/label/matcher.rs
src/label/mod.rs
src/parser/promql.y

- Only [ParseExpr](https://github.com/prometheus/prometheus/blob/0372e259baf014bbade3134fd79bcdfd8cbdef2c/promql/parser/parse.go#L107) is supported yet
- [ParseMetric](https://github.com/prometheus/prometheus/blob/0372e259baf014bbade3134fd79bcdfd8cbdef2c/promql/parser/parse.go#L131),  [ParseMetricSelector](https://github.com/prometheus/prometheus/blob/0372e259baf014bbade3134fd79bcdfd8cbdef2c/promql/parser/parse.go#L150) and [ParseSeriesDesc](https://github.com/prometheus/prometheus/blob/0372e259baf014bbade3134fd79bcdfd8cbdef2c/promql/parser/parse.go#L202) are not supported in Phase 1, so rules won't be included in `promql.y` so far. Thus some structs are useless.

chore(label): remove useless structs

---

src/label/matcher.rs
src/label/mod.rs
src/parser/ast.rs
src/parser/lex.rs
src/parser/parse.rs
src/parser/production.rs
src/parser/promql.y
src/util/mod.rs
src/util/number.rs

- all yacc rules, but `BinaryExpr` and `UnaryExpr` are not ready because of grammar conflicts
- parser test cases
- all cases in prometheus MUST be covered
- the cases which are commented MUST be implemented in the future
- StringLiteral
- NumberLiteral
- VectorSelector
- MatrixSelector
- AggregateExpr
- Preprocessor, Function Call, ParenExpr, Subquery (These will be covered in next PR)
- BinaryExpr and UnaryExpr (These depends on #31 )

feat(parser): yacc rules and tests

---

src/parser/ast.rs
src/parser/parse.rs
src/parser/promql.y

- omit error in yacc file, for grmtools does not support it. See [Major differences](https://softdevteam.github.io/grmtools/master/book/yacccompatibility.html#major-differences)
- fix unary expr conflicts, and unit tests
- fix binary expr rule conflicts

fix: unary grammer conflicts

---

codecov.yml
src/label/matcher.rs
src/parser/ast.rs
src/parser/lex.rs
src/parser/mod.rs
src/parser/parse.rs
src/parser/production.rs
src/parser/promql.y
src/parser/token.rs

- binary expr rules
- all success test cases
- part of `check_ast` function (binary expr logic match)
- rename `TokenType` to `TokenId`, and use a new TokenType tuple struct
- whole `check_ast` function
- support all failed test cases and error information

feat(parser): bin expr and all test cases

---

build.rs
src/label/matcher.rs
src/parser/ast.rs
src/parser/function.rs
src/parser/lex.rs
src/parser/mod.rs
src/parser/parse.rs
src/parser/production.rs
src/parser/promql.y
src/parser/token.rs
src/util/duration.rs
src/util/number.rs

- more test cases for failed scenario
- disable grmtools erros recovery, which will result in different result for same query
- re-format yacc file, especially for indent of `;` and `|`
- some test cases from prometheus official website
[error recovery](https://softdevteam.github.io/grmtools/master/book/errorrecovery.html) will try to repair the invalid promql, and it is unpredictable. Some queries are invalid, but sometimes they will be valid because of the repairing. In order to be stable, the repairing is to be disabled.

feat: disable grmtools error recovery

---

src/util/mod.rs
src/util/visitor.rs

Closes #57 
Define `ExprVisitor` trait, and implement `walk_expr` function that use `ExprVisitor` to traverse the AST

feat: define ExprVisitor trait and implement walk_expr

---

src/label/matcher.rs
src/parser/parse.rs

Go and Rust have some differences in their regex implementation. In Go the following is valid:
```
uri=~"/v[1-9]/.*/{gid}/{uid}"
```
Rust sees the `{gid}` as a bad repetition, it expects a range like {1,4}
```
regex parse error:
/v[1-9]/.*/{gid}/{uid}
^
error: repetition quantifier expects a valid decimal
```
For it to be a valid Rust regex the opening { has to be escaped.
This change adds that escaping.
The implementation is simple, iteration + writing in a result buffer. It is probably not the best of nicest way of doing it, but it straight forward.
Fixes #75

fix: Convert Go regex to Rust regex

---

src/label/matcher.rs
src/label/mod.rs
src/parser/lex.rs
src/parser/parse.rs
src/parser/promql.y

[**MetricQL**](https://docs.victoriametrics.com/keyconcepts/#metricsql) is an enhanced extension of **PromQL**, And is backward-compatible with **PromQL**.
Currently, **MetricQL** already supports using the "**or**" operator to connect label filters as follows:
For example, the following query selects time series with {job="app1",env="prod"} or {job="app2",env="dev"} labels:
> `{job="app1",env="prod" or job="app2",env="dev"}`
A more detailed description of this feature can be found here [MetricsQL filtering-by-multiple-or-filters](https://docs.victoriametrics.com/keyconcepts/#filtering-by-multiple-or-filters)
This PR is to support filtering by multiple “or” filters

feat: add or operator for metric expression

---

src/parser/promql.y

This PR fixes the clippy warnings under `1.79.0`.

style: fix clippy

---

README.md
examples/parser.rs
src/lib.rs
src/util/visitor.rs

When handling `Expr::Binary` in `walk_expr`, the return values from lhs and rhs are ORed (`||`) but it should be `&&`.
For example, let the expression be `foo{l1="v1"} + bar{l2="v2"}`. `walk_expr` will recurse into lhs (`foo`) first and if the return value is `Ok(true)`, it should recurse into rhs (`bar`) but it would not.
Additionally, there was a small inconsistency in the example (newlines between the output), so I fixed it.

fix: handle `Expr::Binary` properly in `walk_expr`

---

Cargo.toml
src/parser/ast.rs

Implement `fmt::Display` for `EvalStmt` for better logging.

refactor: implement `Display` for `EvalStmt`

---

Cargo.toml
src/label/matcher.rs
src/label/mod.rs
src/parser/ast.rs
src/parser/function.rs
src/parser/token.rs
src/parser/value.rs
src/util/duration.rs
tests/ser.rs

Fixes #93 
This patch attempts to add AST serialization to match output of prometheus 3.0 parse_query.

feat: serialize AST to json

---

src/parser/ast.rs
tests/ser.rs

I missed test for aggregation in previous commit and it has some incompatibility with vanilla prometheus.

fix: aggregation serialization

---

src/label/matcher.rs
src/parser/parse.rs

All regular expressions in Prometheus use [RE2 syntax](https://github.com/google/re2/wiki/Syntax).
Regex matches are always fully anchored.

fix: anchor regex string to fully match

---

Cargo.toml
src/label/matcher.rs

In fact the unescape should be handled on lex. But the current impl of lex only verifies if the escape sequence is valid, instead of really escaping them.

fix: unescape regex pattern 

---

src/label/matcher.rs
src/parser/parse.rs

In case `a|b|c` will become `^a|b|c$` instead of `^(a|b|c)$`

fix: wrap regex with parentheses
